name: SSH Test

on: 
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set SSH Environment
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          echo "$PUBLIC_KEY" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
      - name: Connect SSH And Do
        run: |
          pwd
          ls
          ssh -p 10086 -i ~/.ssh/id_rsa root@106.12.118.138
          pwd
          ls
          exit
          
          
   

